version: '3'

services:
  app: 
    build:
      context: web/bot/
      args:
        HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
    ports:
      - 8000:8000
    env_file:
      - .env
    
  web: 
    build:
      context: web/
    ports:
      - 8501:8501
    depends_on:
      - app